# https://github.com/realm/SwiftLint

included: # paths to include during linting. `--path` is ignored if present.
  - Sources
  - analyze
disabled_rules: # rule identifiers to exclude from running
  - todo
  - function_parameter_count
  - trailing_whitespace
line_length: 150
